Explictly sort by semver when finding release asset.
- GitHub claims to always sort release by semver (descending) but we have seen
  situations where this is not the case. Therefore we should be explict about
  sorting in the order we want.
- Improve debuggability by printing release version and asset filename
- Exit with error when multiple assets are found

diff --git a/actions/release/find-asset/entrypoint b/actions/release/find-asset/entrypoint
--- a/actions/release/find-asset/entrypoint
+++ b/actions/release/find-asset/entrypoint
@@ -52,24 +52,51 @@ function find_asset() {
   depth="${2}"
   pattern="${3}"
   strict="${4}"
-  url=$(gh api "repos/${repo}/releases"  \
+
+  release_json=$(gh api "repos/${repo}/releases"  \
     --method GET \
     --paginate \
     | jq -r \
     --arg pattern "${pattern}" \
     --argjson depth "${depth}" \
-    '[ limit($depth; .[] | select( .draft == false )) | .assets | .[] | select(.name | test($pattern)) | .url][0]' )
+    'sort_by(.tag_name | .[1:] | split(".") | map(tonumber))
+    | reverse
+    | map(select(.draft==false))
+    | limit($depth; .)
+    | map(select(.assets | .[] | select(.name | test($pattern))))
+    | .[0]' \
+  )
 
-  if [[ "${url}" == "null" ]]; then
+  if [[ "${release_json}" == "null" ]]; then
       if [[ "${strict}" == "true" ]]; then
-        echo "No matching asset found."
+        echo "Error: no matching asset found for pattern: '${pattern}' on repo: ${repo} and depth: ${depth}."
         exit 1
       fi
     url=""
   fi
-  echo "Asset URL is: " "${url}"
 
-  printf "url=%s\n" "${url}" >> "$GITHUB_OUTPUT"
+  release_version=$(echo "${release_json}" | jq -r '.tag_name')
+
+  assets_json=$(echo "${release_json}" \
+    | jq -r \
+    --arg pattern "${pattern}" \
+    '.assets | map(select(.name|test($pattern)))')
+
+  asset_count=$(echo "${assets_json}" | jq 'length')
+
+  if [[ "${asset_count}" -gt 1 ]]; then
+    echo "Error: expected one asset - found ${asset_count} assets matching pattern: '${pattern}' on ${repo} ${release_version}."
+    echo "${assets_json}" | jq -r '.[] | "- " + (.name)'
+    exit 1
+  fi
+
+  asset_name=$(echo "${assets_json}" | jq -r '.[0].name')
+  asset_url=$(echo "${assets_json}" | jq -r '.[0].url')
+
+  echo "Found asset: '${asset_name}' on ${repo} ${release_version}."
+  echo "Asset URL: ${asset_url}"
+
+  printf "url=%s\n" "${asset_url}" >> "$GITHUB_OUTPUT"
 }
 
 main "${@:-}"
