Add exponential backoff to open-pr action.
- we often see this action fail with graphQL errors if we try to open too many PRs in a short amount of time.

diff --git a/actions/pull-request/open/entrypoint b/actions/pull-request/open/entrypoint
--- a/actions/pull-request/open/entrypoint
+++ b/actions/pull-request/open/entrypoint
@@ -63,12 +63,50 @@ function main() {
 
   git config --global --add safe.directory "${GITHUB_WORKSPACE}"
   pushd "${GITHUB_WORKSPACE}" > /dev/null || true
-    gh pr create \
+    with_backoff gh pr create \
       --title "${title}" \
       --body "${body}" \
       --base "${base}" \
       --label "${label}"
   popd > /dev/null || true
+}
+
+# Retries a command a configurable number of times with backoff.
+#
+# Successive backoffs double the timeout.
+#
+# The rough total time is given by 2^(n-1)*t where n is the maximum number of attempts and t is the timeout between retries
+# At n=8 and t=1 second the total time is about 2^7*1 = 128 seconds, or about two minutes.
+#
+# based on: https://stackoverflow.com/questions/8350942/how-to-re-run-the-curl-command-automatically-when-the-error-occurs/8351489#8351489
+function with_backoff {
+ local max_attempts=8 # about two minutes 
+  local timeout=1 # seconds between retries
+  local attempt=1
+  local exitCode=0
+
+  while (( attempt < max_attempts ))
+  do
+    echo "running command: ${*}"
+    if "$@"
+    then
+      return 0
+    else
+      exitCode=$?
+    fi
+
+    echo "Failed to run command. Retrying in $timeout seconds..." 1>&2
+    sleep $timeout
+    attempt=$(( attempt + 1 ))
+    timeout=$(( timeout * 2 ))
+  done
+
+  if [[ $exitCode != 0 ]]
+  then
+    echo "Failed after ${attempt} attempts" 1>&2
+  fi
+
+  return $exitCode
 }
 
 main "${@:-}"
